module.exports = {
  apps: [
    {
      name: 'lead-engine-auto-capture',
      script: 'node',
      args: '--env-file=.env.local --experimental-strip-types --experimental-default-type=module scripts/outbound/run-auto-capture-daemon.ts --mode=auto-capture',
      cwd: __dirname,
      autorestart: true,
      kill_timeout: 10000,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: 'lead-engine-gemini-email',
      script: 'node',
      args: '--env-file=.env.local --experimental-strip-types --experimental-default-type=module scripts/outbound/run-auto-capture-daemon.ts --mode=gemini-email',
      cwd: __dirname,
      autorestart: true,
      kill_timeout: 10000,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: 'lead-engine-slot-scheduler',
      script: 'node',
      args: '--env-file=.env.local --experimental-strip-types --experimental-default-type=module scripts/outbound/run-auto-capture-daemon.ts --mode=slot-scheduler',
      cwd: __dirname,
      autorestart: true,
      kill_timeout: 10000,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: 'lead-engine-ig-whatsapp',
      script: 'node',
      args: '--env-file=.env.local --experimental-strip-types --experimental-default-type=module scripts/outbound/run-auto-capture-daemon.ts --mode=instagram-whatsapp',
      cwd: __dirname,
      autorestart: true,
      kill_timeout: 10000,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: 'lead-engine-db-backup',
      script: 'node',
      args: '--env-file=.env.local --experimental-strip-types --experimental-default-type=module scripts/outbound/backup-database.ts',
      cwd: __dirname,
      autorestart: false,
      cron_restart: '0 3 * * *',
    },
  ],
}
